name: Create Anime Video

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy hàng ngày lúc 00:00 UTC
  workflow_dispatch:      # Cho phép chạy thủ công

jobs:
  create-video:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          sudo apt-get install -y fonts-liberation
          sudo apt-get install -y ttf-mscorefonts-installer
          sudo fc-cache -f -v
          
      - name: Configure ImageMagick policy
        run: |
          sudo sed -i 's/<policy domain="path" rights="none" pattern="@\*"/<policy domain="path" rights="read|write" pattern="@*"/g' /etc/ImageMagick-6/policy.xml
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account and client secrets files
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' > serviceAccountKey.json
          echo '${{ secrets.CLIENT_SECRETS }}' > client_secrets.json
          echo '${{ secrets.OAUTH_TOKEN }}' > oauth_token.json

      - name: Create video and upload
        env:
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
        run: python main.py
        
      - name: Upload video artifact
        uses: actions/upload-artifact@v3
        with:
          name: anime-video
          path: '*.mp4'
